# Generated by Django 3.2.9 on 2022-01-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
