# Generated by Django 3.2.9 on 2022-01-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='mail',
        ),
    ]
