# Generated by Django 3.2.9 on 2021-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
    ]
