# Generated by Django 3.2.9 on 2021-12-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society_problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('flat', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=50)),
                ('solution', models.CharField(max_length=50)),
            ],
        ),
    ]
