# Generated by Django 3.2.9 on 2021-12-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society_members_information_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatno', models.CharField(max_length=50)),
                ('familymember1', models.CharField(max_length=50)),
                ('numberofmember', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
