# Generated by Django 3.2.9 on 2021-12-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_society_members_information_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='society_members_information_management',
            old_name='familymember1',
            new_name='member',
        ),
    ]
