# Generated by Django 3.2.9 on 2021-12-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_society_members_information_management_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='competitions_in_society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('disc', models.TextField(max_length=50)),
                ('pics', models.FileField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
