# Generated by Django 3.2.9 on 2021-12-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_pics_competitions_in_society_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitions_in_society',
            old_name='pic',
            new_name='pics',
        ),
    ]
