# Generated by Django 3.2.9 on 2021-12-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_pic_competitions_in_society_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions_in_society',
            name='pics',
            field=models.FileField(blank=True, null=True, upload_to='event'),
        ),
    ]
