# Generated by Django 3.2.9 on 2021-12-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_competitions_in_society_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions_in_society',
            name='pics',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
    ]
