# Generated by Django 3.2.9 on 2021-12-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_competitions_in_society_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitions_in_society',
            old_name='pics',
            new_name='pic',
        ),
    ]
