# Generated by Django 3.2.9 on 2022-01-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_notifications_disc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='competitions_in_society',
        ),
    ]
