# Generated by Django 3.2.9 on 2022-01-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_competitions_in_society'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Society_problem',
        ),
    ]
